ALTER TABLE review RENAME TO approve;
ALTER TABLE daily_count RENAME TO action;
ALTER TABLE weekly_result RENAME TO achievement;
ALTER SEQUENCE daily_count_daily_count_id_seq RENAME TO action_action_id_seq;
ALTER SEQUENCE weekly_result_weekly_result_id_seq RENAME TO achievement_achievement_id_seq;
ALTER TABLE approve RENAME COLUMN review_id TO approve_id;
ALTER TABLE action RENAME COLUMN daily_count_id TO action_id;
ALTER TABLE action RENAME COLUMN account_id TO developer_id;
ALTER TABLE achievement RENAME COLUMN weekly_result_id TO achievement_id;
ALTER TABLE achievement RENAME COLUMN account_id TO developer_id;
ALTER TABLE approve RENAME CONSTRAINT review_author_id_fkey TO approve_author_id_fkey;
ALTER TABLE approve RENAME CONSTRAINT review_pkey TO approve_pkey;
ALTER TABLE approve RENAME CONSTRAINT review_pull_request_id_fkey TO approve_pull_request_id_fkey;
ALTER TABLE action RENAME CONSTRAINT daily_count_account_id_fkey TO action_developer_id_fkey;
ALTER TABLE action RENAME CONSTRAINT daily_count_pkey TO action_pkey;
ALTER TABLE action RENAME CONSTRAINT daily_count_repo_id_fkey TO action_repo_id_fkey;
ALTER TABLE achievement RENAME CONSTRAINT weekly_result_account_id_fkey TO achievement_developer_id_fkey;
ALTER TABLE achievement RENAME CONSTRAINT weekly_result_pkey TO achievement_pkey;
ALTER TABLE achievement RENAME CONSTRAINT weekly_result_repo_id_fkey TO achievement_repo_id_fkey;
