ALTER TABLE review ALTER COLUMN author_id SET NOT NULL;
ALTER TABLE review ALTER COLUMN pull_request_id SET NOT NULL;

ALTER TABLE comment ALTER COLUMN commit_hash SET NOT NULL;
ALTER TABLE comment ALTER COLUMN author_id SET NOT NULL;

ALTER TABLE commit ALTER COLUMN author_id SET NOT NULL;
ALTER TABLE commit ALTER COLUMN pull_request_id SET NOT NULL;
ALTER TABLE commit ALTER COLUMN repo_id SET NOT NULL;

ALTER TABLE pull_request ALTER COLUMN author_id SET NOT NULL;
ALTER TABLE pull_request ALTER COLUMN repo_id SET NOT NULL;
